version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
  ngrok:
    image: ngrok/ngrok:latest
    network_mode: host
    depends_on:
      - rabbitmq
    environment:
      - NGROK_AUTHTOKEN=${TOKEN_NGROK}
    command: tcp 5672
    restart: unless-stopped
